[workspace]
resolver = "2"
members = ["crates/issuectl", "crates/issuectl-core"]

[workspace.package]
version = "0.12.0"
edition = "2021"
rust-version = "1.82"
authors = ["Jari Mustonen <jari.mustonen@iki.fi>"]
license = "MIT"
repository = "https://github.com/jarimustonen/issuectl"
homepage = "https://github.com/jarimustonen/issuectl"

[profile.release]
strip = true
lto = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
