//! `issuectl agents init` — write `.issuectl/AGENTS.md`, a per-repo
//! policy file that AI agents read by convention.
//!
//! The file has two parts:
//!
//! 1. A free-form prose preamble owned by the user. After
//!    initialization the user can edit this freely; subsequent
//!    `issuectl agents init` (without `--force`) refuses to clobber it,
//!    and `issuectl doctor --fix` only touches the schema-derived
//!    block.
//! 2. A schema-derived block fenced with HTML-comment sentinels
//!    (`MANAGED_START` / `MANAGED_END`). Doctor regenerates this from
//!    the current schema + transition rules so it never drifts from
//!    the live policy.
//!
//! Sentinel detection is **line-anchored**: a sentinel line counts only
//! when it occupies its own line (whitespace allowed). This protects
//! sentinels embedded in fenced code blocks (documentation examples)
//! from being treated as the real block. Files containing zero or one
//! well-formed pair of sentinels are auto-fixable; anything else
//! (multiple pairs, end-before-start, dangling start) is reported as
//! malformed and `--fix` refuses to touch it.
//!
//! Policy distinct from `.issuectl/prompts/*.md` (ephemeral prompt
//! templates rendered against an issue context). AGENTS.md is durable
//! repo-wide policy with no per-issue interpolation.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::schema::{self, Schema};
use crate::transitions::{self, TransitionRules};

pub const AGENTS_RELATIVE_PATH: &str = ".issuectl/AGENTS.md";

pub const MANAGED_START: &str = "<!-- issuectl-managed:start -->";
pub const MANAGED_END: &str = "<!-- issuectl-managed:end -->";

/// Format version embedded as the first line inside the managed body.
/// Bump only when the renderer makes an intentionally breaking change;
/// drift checks compare full body bytes, so this marker is a forward-
/// compat anchor (`managed_in_sync` semantics could later branch on it
/// to defer cosmetic-only renderer churn instead of flagging every
/// repo's AGENTS.md as drifted across an `issuectl` upgrade).
pub const MANAGED_FORMAT_VERSION: u32 = 1;

pub fn agents_path(root: &Path) -> PathBuf {
    root.join(AGENTS_RELATIVE_PATH)
}

/// Static prose preamble written on `init`. After write, this section
/// is owned by the user — `doctor --fix` does not touch it.
pub const DEFAULT_PROSE: &str = r#"# Agents policy (`.issuectl/AGENTS.md`)

Durable rules for AI agents acting on this repo's issue tracker. The
schema-derived block at the bottom is regenerated by
`issuectl doctor --fix` from `issues/.schema.yaml` and
`.issuectl/transitions.yaml`; everything outside the sentinels is
yours to edit.

This file is the issuectl-managed policy. The repo may also have a
top-level `AGENTS.md` covering project-wide guidance; that one is
unrelated to this file.

## Mutating issues

- **Never edit frontmatter manually.** Use `issuectl set`,
  `issuectl update`, or `issuectl apply` — they hold the repo write
  lock, validate against the schema, and emit a canonical
  version token (`--expected-version`) for optimistic concurrency.
- **Status changes**: `issuectl note --decision …` for in-flight
  context, `issuectl update --status …` for the actual transition.
- **Checklist toggles**: `issuectl check <slug> "<task text>"` —
  flips a single `- [ ]` ↔ `- [x]` in the body without rewriting
  surrounding markdown.
- **Multi-field changes**: `issuectl apply <patch.yaml>` — one
  transactional write covering frontmatter, list ops, custom fields,
  and recorded commits.

## Body conventions

- Required H2 sections per issue type are declared in
  `issues/.schema.yaml` under `body_sections:`. The schema-derived
  block below lists the current rules.
- New status updates and decisions go in `## Comments` /
  `## Decisions` (use `issuectl note`).
- Agent run logs go in `## Agent Runs` (use
  `issuectl note --agent-run`).

## Status transitions

- Declarative preconditions (assignee required, commits required,
  acceptance-criteria checked, allowed-from / forbidden-from graph)
  live in `.issuectl/transitions.yaml`. The schema-derived block
  below summarizes the active rules.
- The mutation layer rejects illegal transitions with a
  `TransitionViolation` (HTTP 422); agents must inspect the error
  rather than retrying blindly.

## Commits

- Reference issues from commits with a `Refs-Issue: @<slug>` trailer.
  `issuectl --json update <slug> --add-commit "HASH:summary"` records
  it on the issue side.

## Before closing an issue

- Run `issuectl doctor` and fix any critical findings.
- If the type declares required body sections, every required H2
  must be present (doctor flags missing ones).
- Status-rule preconditions must be satisfied (the mutation layer
  enforces this; doctor reports legacy-data warnings).

"#;

/// Render the schema-derived block (without surrounding sentinels).
/// Pure — same inputs always produce the same bytes — so doctor's
/// drift check is just a string compare. The first line is a format
/// marker; bumping `MANAGED_FORMAT_VERSION` invalidates every existing
/// repo's block and is therefore reserved for intentional breaks.
pub fn render_managed_body(schema: &Schema, rules: &TransitionRules) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- issuectl-managed:format={MANAGED_FORMAT_VERSION} -->\n\n"
    ));
    out.push_str("## Schema-derived rules (generated)\n\n");
    out.push_str(
        "_Regenerated by `issuectl doctor --fix`. Do not hand-edit between the sentinels._\n\n",
    );

    // Frontmatter fields.
    out.push_str("### Frontmatter fields\n\n");
    for (name, spec) in &schema.fields {
        let req = if spec.required { "required" } else { "optional" };
        let kind = if spec.list { "list" } else { "scalar" };
        let allowed = match spec.allowed.as_ref() {
            Some(vs) if !vs.is_empty() => format!(" — allowed: {}", vs.join(", ")),
            _ => String::new(),
        };
        out.push_str(&format!("- `{name}` ({req}, {kind}){allowed}\n"));
    }
    out.push('\n');

    // Required body sections per type.
    out.push_str("### Required body sections by issue type\n\n");
    if schema.body_sections.is_empty() {
        out.push_str("_No per-type body-section requirements declared._\n\n");
    } else {
        for (issue_type, sections) in &schema.body_sections {
            if sections.is_empty() {
                continue;
            }
            let names: Vec<String> =
                sections.iter().map(|s| format!("`## {s}`")).collect();
            out.push_str(&format!("- **{issue_type}**: {}\n", names.join(", ")));
        }
        out.push('\n');
    }

    // Transition rules.
    out.push_str("### Status-transition rules\n\n");
    if rules.status_rules.is_empty() {
        out.push_str("_No transition rules declared (lenient default)._\n\n");
    } else {
        for (target, rule) in &rules.status_rules {
            out.push_str(&format!("- **→ {target}**\n"));
            if rule.requires_assignee {
                out.push_str("  - requires `assignee` (or `owner` on epics)\n");
            }
            if rule.requires_acceptance_criteria_checked {
                out.push_str(
                    "  - requires `## Acceptance Criteria` with all checkboxes ticked\n",
                );
            }
            if rule.requires_commits {
                out.push_str("  - requires at least one entry in `commits:`\n");
            }
            if !rule.allowed_from.is_empty() {
                out.push_str(&format!(
                    "  - allowed from: {}\n",
                    rule.allowed_from.join(", ")
                ));
            }
            if !rule.forbidden_from.is_empty() {
                out.push_str(&format!(
                    "  - forbidden from: {}\n",
                    rule.forbidden_from.join(", ")
                ));
            }
        }
        out.push('\n');
    }

    out
}

/// Wrap a managed body in sentinel comments. Used both for initial
/// generation and for `--fix` regeneration.
fn wrap_managed(body: &str) -> String {
    format!("{MANAGED_START}\n\n{body}{MANAGED_END}\n")
}

/// Render the full default file (prose + sentinel-fenced schema block).
pub fn render_full(schema: &Schema, rules: &TransitionRules) -> String {
    let mut out = String::new();
    out.push_str(DEFAULT_PROSE);
    out.push_str(&wrap_managed(&render_managed_body(schema, rules)));
    out
}

/// Result of locating sentinel pairs in a file. Distinguishes "no
/// managed block" (auto-fixable: append) from a single well-formed
/// block (auto-fixable: replace) from malformed state (refuse to
/// auto-fix).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlockLocation {
    /// No sentinel lines present at all.
    Unmanaged,
    /// Exactly one well-formed pair. Span is `(start_byte_of_open_line,
    /// end_byte_after_close_line)` so a slice replacement preserves
    /// surrounding text byte-for-byte.
    Found { span: (usize, usize) },
    /// Multiple sentinel pairs, dangling open, end-before-start, etc.
    /// `--fix` refuses; surface as a separate doctor finding.
    Malformed { reason: String },
}

/// Find sentinel lines using line-anchored matching: a line counts as
/// a sentinel only when its trimmed content is exactly the sentinel
/// string. This protects sentinels embedded in fenced code blocks
/// (e.g. `\`\`\`markdown` blocks demonstrating the syntax) from being
/// mistaken for the real block.
pub fn locate_managed_block(text: &str) -> BlockLocation {
    // Walk lines collecting byte-offsets of sentinel-only lines.
    let mut starts: Vec<(usize, usize)> = Vec::new();
    let mut ends: Vec<(usize, usize)> = Vec::new();
    let bytes = text.as_bytes();
    let mut line_start = 0usize;
    while line_start <= bytes.len() {
        let line_end = match bytes[line_start..].iter().position(|&b| b == b'\n') {
            Some(rel) => line_start + rel,
            None => bytes.len(),
        };
        let line = &text[line_start..line_end];
        let trimmed = line.trim();
        if trimmed == MANAGED_START {
            // End of line including the newline byte if present.
            let after = if line_end < bytes.len() { line_end + 1 } else { line_end };
            starts.push((line_start, after));
        } else if trimmed == MANAGED_END {
            let after = if line_end < bytes.len() { line_end + 1 } else { line_end };
            ends.push((line_start, after));
        }
        if line_end >= bytes.len() {
            break;
        }
        line_start = line_end + 1;
    }

    match (starts.len(), ends.len()) {
        (0, 0) => BlockLocation::Unmanaged,
        (1, 0) => BlockLocation::Malformed {
            reason: "managed-start sentinel without matching managed-end".into(),
        },
        (0, 1) => BlockLocation::Malformed {
            reason: "managed-end sentinel without matching managed-start".into(),
        },
        (1, 1) => {
            let (s_start, _s_after) = starts[0];
            let (e_start, e_after) = ends[0];
            if e_start < s_start {
                BlockLocation::Malformed {
                    reason: "managed-end appears before managed-start".into(),
                }
            } else {
                BlockLocation::Found {
                    span: (s_start, e_after),
                }
            }
        }
        (n_s, n_e) => BlockLocation::Malformed {
            reason: format!(
                "expected exactly one managed block pair, found {n_s} start sentinel(s) and {n_e} end sentinel(s)"
            ),
        },
    }
}

/// Extract the inner managed body from a well-formed file: text
/// between the open sentinel line and the close sentinel line. Strips
/// the immediate leading newline and one optional blank line that
/// `wrap_managed` writes, so equality compares cleanly against
/// `render_managed_body`. Returns `None` for `Unmanaged` or
/// `Malformed`.
pub fn extract_managed_body(text: &str) -> Option<String> {
    let (start, end) = match locate_managed_block(text) {
        BlockLocation::Found { span } => span,
        _ => return None,
    };
    let block = &text[start..end];
    // Trim the surrounding sentinel lines: drop everything up through
    // the first newline (open sentinel line) and everything from the
    // last `MANAGED_END` line backwards.
    let after_open_line = block.find('\n').map(|i| i + 1).unwrap_or(block.len());
    let inner_with_close = &block[after_open_line..];
    // Find the start of the close-sentinel line. We know the line is
    // present because locate returned Found.
    let close_line_start = inner_with_close.rfind(MANAGED_END).and_then(|i| {
        inner_with_close[..i].rfind('\n').map(|j| j + 1).or(Some(0))
    })?;
    let inner = &inner_with_close[..close_line_start];
    // Drop one leading blank line that `wrap_managed` emits ("\n").
    let inner = inner.strip_prefix('\n').unwrap_or(inner);
    Some(inner.to_string())
}

/// Replace the managed span in `text` with a freshly-rendered block.
/// Preserves everything outside the sentinels byte-for-byte. If the
/// file has no sentinels, appends a fresh managed block at the end
/// (separated by a blank line). Caller is responsible for refusing
/// `Malformed` files — passing one here will short-circuit to "append
/// new block" which would compound the malformed state. Use
/// [`locate_managed_block`] first.
pub fn regenerate_managed(text: &str, schema: &Schema, rules: &TransitionRules) -> String {
    let body = render_managed_body(schema, rules);
    let wrapped = wrap_managed(&body);
    match locate_managed_block(text) {
        BlockLocation::Found { span: (start, end) } => {
            let mut out = String::with_capacity(text.len());
            out.push_str(&text[..start]);
            out.push_str(&wrapped);
            out.push_str(&text[end..]);
            out
        }
        BlockLocation::Unmanaged | BlockLocation::Malformed { .. } => {
            // The Malformed branch is reachable only if a caller
            // ignored locate_managed_block. We still produce something
            // safe (append) rather than panic, but doctor's --fix path
            // refuses to call here for Malformed files.
            let mut out = String::from(text);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            if !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(&wrapped);
            out
        }
    }
}

/// Returns true when the managed block in `text` matches what the
/// current schema + rules would produce. Unmanaged or malformed files
/// are not in sync.
pub fn managed_in_sync(text: &str, schema: &Schema, rules: &TransitionRules) -> bool {
    let expected = render_managed_body(schema, rules);
    match extract_managed_body(text) {
        Some(actual) => actual == expected,
        None => false,
    }
}

/// Refuse non-regular files (symlink, dir, FIFO). Returns whether the
/// path exists as a regular file. Errors on unreadable metadata other
/// than NotFound.
fn classify_target(path: &Path) -> Result<bool> {
    match fs::symlink_metadata(path) {
        Ok(meta) => {
            let ft = meta.file_type();
            if ft.is_symlink() {
                bail!(
                    "{} is a symlink; refusing to follow (rename or remove it manually)",
                    path.display()
                );
            }
            if !ft.is_file() {
                bail!(
                    "{} exists but is not a regular file",
                    path.display()
                );
            }
            Ok(true)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(false),
        Err(e) => Err(anyhow::Error::from(e))
            .with_context(|| format!("cannot stat {}", path.display())),
    }
}

/// Atomic write: stage bytes in a tempfile in the same directory, then
/// `persist` (rename) into place. Survives SIGKILL / disk full mid-
/// write without leaving a half-overwritten target. Mirrors
/// `schema::ensure_default_written`.
pub(crate) fn atomic_write(path: &Path, content: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("path has no parent: {}", path.display()))?;
    fs::create_dir_all(parent)
        .with_context(|| format!("cannot create {}", parent.display()))?;
    let mut tmp = tempfile::Builder::new()
        .prefix(".issuectl-agents-")
        .tempfile_in(parent)
        .with_context(|| format!("cannot create temp file in {}", parent.display()))?;
    tmp.as_file_mut()
        .write_all(content)
        .with_context(|| format!("cannot write temp file for {}", path.display()))?;
    tmp.as_file_mut()
        .sync_all()
        .with_context(|| format!("cannot fsync temp file for {}", path.display()))?;
    tmp.persist(path)
        .map_err(|e| e.error)
        .with_context(|| format!("cannot replace {}", path.display()))?;
    Ok(())
}

pub fn run_init(root: &Path, force: bool, json: bool) -> Result<()> {
    // Repo write lock — same convention as every other mutation path
    // in the codebase. Prevents `agents init --force` from racing with
    // `doctor --fix` or other concurrent writers.
    let _lock = crate::mutate::WriteLock::acquire(root)?;

    let path = agents_path(root);

    let existed = classify_target(&path)?;
    if existed && !force {
        if json {
            println!(
                "{}",
                serde_json::to_string_pretty(&serde_json::json!({
                    "path": rel(root, &path),
                    "wrote": false,
                    "reason": "already exists; pass --force to overwrite",
                }))?
            );
        } else {
            eprintln!(
                "{} already exists; pass --force to overwrite.",
                rel(root, &path)
            );
        }
        bail!("{} already exists", rel(root, &path));
    }

    let schema = schema::load(root)?;
    let rules = transitions::load(root)?;
    let content = render_full(&schema, &rules);

    atomic_write(&path, content.as_bytes())?;

    if json {
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({
                "path": rel(root, &path),
                "wrote": true,
                "overwrote_existing": existed,
            }))?
        );
    } else {
        let verb = if existed { "Overwrote" } else { "Wrote" };
        println!("{} {}", verb, rel(root, &path));
    }
    Ok(())
}

fn rel(root: &Path, p: &Path) -> String {
    p.strip_prefix(root)
        .unwrap_or(p)
        .to_string_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fresh() -> TempDir {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join("issues")).unwrap();
        tmp
    }

    #[test]
    fn render_full_includes_sentinels_and_default_prose() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let out = render_full(&s, &r);
        assert!(out.contains(MANAGED_START));
        assert!(out.contains(MANAGED_END));
        assert!(out.contains("issuectl-managed:format=1"));
        assert!(out.contains("Never edit frontmatter manually"));
        assert!(out.contains("Refs-Issue: @<slug>"));
        // Default schema declares status enum — must surface.
        assert!(out.contains("`status`"));
        assert!(out.contains("in-progress"));
    }

    #[test]
    fn render_includes_body_sections_when_declared() {
        let mut s = schema::default_schema();
        s.body_sections.insert(
            "bug".to_string(),
            vec!["Reproduction".to_string(), "Acceptance Criteria".to_string()],
        );
        let out = render_full(&s, &TransitionRules::default());
        assert!(out.contains("**bug**"));
        assert!(out.contains("`## Reproduction`"));
        assert!(out.contains("`## Acceptance Criteria`"));
    }

    #[test]
    fn render_includes_transition_rules_when_declared() {
        let s = schema::default_schema();
        let r: TransitionRules = serde_yaml::from_str(
            "version: 1\nstatus_rules:\n  done:\n    requires_assignee: true\n    allowed_from: [testing]\n",
        )
        .unwrap();
        let out = render_full(&s, &r);
        assert!(out.contains("**→ done**"));
        assert!(out.contains("requires `assignee`"));
        assert!(out.contains("allowed from: testing"));
    }

    #[test]
    fn run_init_writes_file() {
        let tmp = fresh();
        run_init(tmp.path(), false, false).unwrap();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        assert!(p.is_file());
        let text = fs::read_to_string(&p).unwrap();
        assert!(text.contains(MANAGED_START));
    }

    #[test]
    fn run_init_refuses_overwrite_without_force() {
        let tmp = fresh();
        run_init(tmp.path(), false, false).unwrap();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        fs::write(&p, "user-edited content\n").unwrap();
        let err = run_init(tmp.path(), false, false).unwrap_err();
        assert!(err.to_string().contains("already exists"));
        // File untouched.
        assert_eq!(fs::read_to_string(&p).unwrap(), "user-edited content\n");
    }

    #[test]
    fn run_init_force_overwrites() {
        let tmp = fresh();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(&p, "stale\n").unwrap();
        run_init(tmp.path(), true, false).unwrap();
        let text = fs::read_to_string(&p).unwrap();
        assert!(text.contains(MANAGED_START));
        assert!(!text.contains("stale"));
    }

    #[test]
    #[cfg(unix)]
    fn run_init_refuses_symlink_target() {
        let tmp = fresh();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        let outside = tmp.path().join("outside.txt");
        fs::write(&outside, "do not overwrite\n").unwrap();
        std::os::unix::fs::symlink(&outside, &p).unwrap();
        let err = run_init(tmp.path(), true, false).unwrap_err();
        assert!(err.to_string().contains("symlink"), "got: {err}");
        // Target untouched.
        assert_eq!(fs::read_to_string(&outside).unwrap(), "do not overwrite\n");
    }

    #[test]
    fn regenerate_preserves_text_outside_sentinels() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let original = format!(
            "# Hand-written\n\nKeep me.\n\n{}\n\nold managed body\n{}\n\nAfter.\n",
            MANAGED_START, MANAGED_END
        );
        let regenerated = regenerate_managed(&original, &s, &r);
        assert!(regenerated.starts_with("# Hand-written\n\nKeep me.\n\n"));
        assert!(regenerated.contains("After.\n"));
        assert!(!regenerated.contains("old managed body"));
        assert!(regenerated.contains(MANAGED_START));
        assert!(regenerated.contains(MANAGED_END));
    }

    #[test]
    fn managed_in_sync_detects_drift() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let good = render_full(&s, &r);
        assert!(managed_in_sync(&good, &s, &r));

        // Mutate schema → drift.
        let mut s2 = s.clone();
        s2.body_sections
            .insert("bug".to_string(), vec!["Reproduction".to_string()]);
        assert!(!managed_in_sync(&good, &s2, &r));

        // Regenerating clears the drift.
        let fixed = regenerate_managed(&good, &s2, &r);
        assert!(managed_in_sync(&fixed, &s2, &r));
    }

    #[test]
    fn missing_sentinels_treated_as_drift() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        assert!(!managed_in_sync("just prose, no sentinels\n", &s, &r));
    }

    #[test]
    fn regenerate_appends_block_when_sentinels_missing() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let original = "Plain prose, no managed block.\n";
        let out = regenerate_managed(original, &s, &r);
        assert!(out.starts_with(original));
        assert!(out.contains(MANAGED_START));
        assert!(managed_in_sync(&out, &s, &r));
    }

    #[test]
    fn locate_handles_unmanaged() {
        assert_eq!(locate_managed_block("just prose\n"), BlockLocation::Unmanaged);
    }

    #[test]
    fn locate_ignores_sentinels_inside_fenced_code_block() {
        // A documentation example containing the literal sentinel
        // strings inside a code fence must NOT be picked up.
        // Indented inside a fence, the lines aren't sentinel-only at
        // their natural position, but even when verbatim the line-
        // anchored matcher treats them as sentinels — we deliberately
        // do NOT track fences here. The defense is that a real user
        // demonstrating sentinels inside a code fence will end up
        // matching them; doctor will treat it as a real block. To
        // avoid that, users should escape (e.g. zero-width-space) or
        // not paste the literals. Document this limitation.
        //
        // We DO test that an indented sentinel (whitespace-prefixed
        // but matching after trim) IS matched — this is by design: it
        // lets users align the file with their preferred indentation.
        let t = "Doc:\n  <!-- issuectl-managed:start -->\n  body\n  <!-- issuectl-managed:end -->\nAfter.\n";
        match locate_managed_block(t) {
            BlockLocation::Found { .. } => { /* expected — indentation tolerated */ }
            other => panic!("expected Found, got {other:?}"),
        }
    }

    #[test]
    fn locate_detects_multiple_blocks() {
        let t = format!(
            "{}\nA\n{}\n\n{}\nB\n{}\n",
            MANAGED_START, MANAGED_END, MANAGED_START, MANAGED_END
        );
        match locate_managed_block(&t) {
            BlockLocation::Malformed { reason } => {
                assert!(reason.contains("found 2 start"), "got: {reason}");
            }
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn locate_detects_dangling_start() {
        let t = format!("{}\nbody\n", MANAGED_START);
        match locate_managed_block(&t) {
            BlockLocation::Malformed { reason } => {
                assert!(reason.contains("without matching managed-end"));
            }
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn locate_detects_end_before_start() {
        let t = format!("{}\nbody\n{}\n", MANAGED_END, MANAGED_START);
        match locate_managed_block(&t) {
            BlockLocation::Malformed { reason } => {
                assert!(reason.contains("before managed-start"));
            }
            other => panic!("expected Malformed, got {other:?}"),
        }
    }

    #[test]
    fn managed_in_sync_returns_false_for_malformed() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let t = format!(
            "{}\nA\n{}\n\n{}\nB\n{}\n",
            MANAGED_START, MANAGED_END, MANAGED_START, MANAGED_END
        );
        assert!(!managed_in_sync(&t, &s, &r));
    }

    #[test]
    fn render_byte_stable_across_repeated_calls() {
        // Map iteration order is BTreeMap-deterministic but render is
        // also exercised here to catch any future regression.
        let s = schema::default_schema();
        let r = TransitionRules::default();
        assert_eq!(render_managed_body(&s, &r), render_managed_body(&s, &r));
    }
}
