//! `issuectl agents init` — write `.issuectl/AGENTS.md`, a per-repo
//! policy file that AI agents read by convention.
//!
//! The file has two parts:
//!
//! 1. A free-form prose preamble owned by the user. After
//!    initialization the user can edit this freely; subsequent
//!    `issuectl agents init` (without `--force`) refuses to clobber it,
//!    and `issuectl doctor --fix` only touches the schema-derived
//!    block.
//! 2. A schema-derived block fenced with HTML-comment sentinels
//!    (`MANAGED_START` / `MANAGED_END`). Doctor regenerates this from
//!    the current schema + transition rules so it never drifts from
//!    the live policy.
//!
//! Policy distinct from `.issuectl/prompts/*.md` (ephemeral prompt
//! templates rendered against an issue context). AGENTS.md is durable
//! repo-wide policy with no per-issue interpolation.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{bail, Context, Result};

use crate::schema::{self, Schema};
use crate::transitions::{self, TransitionRules};

pub const AGENTS_RELATIVE_PATH: &str = ".issuectl/AGENTS.md";

pub const MANAGED_START: &str = "<!-- issuectl-managed:start -->";
pub const MANAGED_END: &str = "<!-- issuectl-managed:end -->";

pub fn agents_path(root: &Path) -> PathBuf {
    root.join(AGENTS_RELATIVE_PATH)
}

/// Static prose preamble written on `init`. After write, this section
/// is owned by the user — `doctor --fix` does not touch it.
pub const DEFAULT_PROSE: &str = r#"# Agents policy (`.issuectl/AGENTS.md`)

Durable rules for AI agents acting on this repo's issue tracker. The
schema-derived block at the bottom is regenerated by
`issuectl doctor --fix` from `issues/.schema.yaml` and
`.issuectl/transitions.yaml`; everything outside the sentinels is
yours to edit.

This file is the issuectl-managed policy. The repo may also have a
top-level `AGENTS.md` covering project-wide guidance; that one is
unrelated to this file.

## Mutating issues

- **Never edit frontmatter manually.** Use `issuectl set`,
  `issuectl update`, or `issuectl apply` — they hold the repo write
  lock, validate against the schema, and emit a canonical
  version token (`--expected-version`) for optimistic concurrency.
- **Status changes**: `issuectl note --decision …` for in-flight
  context, `issuectl update --status …` for the actual transition.
- **Checklist toggles**: `issuectl check <slug> "<task text>"` —
  flips a single `- [ ]` ↔ `- [x]` in the body without rewriting
  surrounding markdown.
- **Multi-field changes**: `issuectl apply <patch.yaml>` — one
  transactional write covering frontmatter, list ops, custom fields,
  and recorded commits.

## Body conventions

- Required H2 sections per issue type are declared in
  `issues/.schema.yaml` under `body_sections:`. The schema-derived
  block below lists the current rules.
- New status updates and decisions go in `## Comments` /
  `## Decisions` (use `issuectl note`).
- Agent run logs go in `## Agent Runs` (use
  `issuectl note --agent-run`).

## Status transitions

- Declarative preconditions (assignee required, commits required,
  acceptance-criteria checked, allowed-from / forbidden-from graph)
  live in `.issuectl/transitions.yaml`. The schema-derived block
  below summarizes the active rules.
- The mutation layer rejects illegal transitions with a
  `TransitionViolation` (HTTP 422); agents must inspect the error
  rather than retrying blindly.

## Commits

- Reference issues from commits with a `Refs-Issue: @<slug>` trailer.
  `issuectl --json update <slug> --add-commit "HASH:summary"` records
  it on the issue side.

## Before closing an issue

- Run `issuectl doctor` and fix any critical findings.
- If the type declares required body sections, every required H2
  must be present (doctor flags missing ones).
- Status-rule preconditions must be satisfied (the mutation layer
  enforces this; doctor reports legacy-data warnings).

"#;

/// Render the schema-derived block (without surrounding sentinels).
/// Pure — same inputs always produce the same bytes — so doctor's
/// drift check is just a string compare.
pub fn render_managed_body(schema: &Schema, rules: &TransitionRules) -> String {
    let mut out = String::new();
    out.push_str("## Schema-derived rules (generated)\n\n");
    out.push_str(
        "_Regenerated by `issuectl doctor --fix`. Do not hand-edit between the sentinels._\n\n",
    );

    // Frontmatter fields.
    out.push_str("### Frontmatter fields\n\n");
    for (name, spec) in &schema.fields {
        let req = if spec.required { "required" } else { "optional" };
        let kind = if spec.list { "list" } else { "scalar" };
        let allowed = match spec.allowed.as_ref() {
            Some(vs) if !vs.is_empty() => format!(" — allowed: {}", vs.join(", ")),
            _ => String::new(),
        };
        out.push_str(&format!("- `{name}` ({req}, {kind}){allowed}\n"));
    }
    out.push('\n');

    // Required body sections per type.
    out.push_str("### Required body sections by issue type\n\n");
    if schema.body_sections.is_empty() {
        out.push_str("_No per-type body-section requirements declared._\n\n");
    } else {
        for (issue_type, sections) in &schema.body_sections {
            if sections.is_empty() {
                continue;
            }
            let names: Vec<String> =
                sections.iter().map(|s| format!("`## {s}`")).collect();
            out.push_str(&format!("- **{issue_type}**: {}\n", names.join(", ")));
        }
        out.push('\n');
    }

    // Transition rules.
    out.push_str("### Status-transition rules\n\n");
    if rules.status_rules.is_empty() {
        out.push_str("_No transition rules declared (lenient default)._\n\n");
    } else {
        for (target, rule) in &rules.status_rules {
            out.push_str(&format!("- **→ {target}**\n"));
            if rule.requires_assignee {
                out.push_str("  - requires `assignee` (or `owner` on epics)\n");
            }
            if rule.requires_acceptance_criteria_checked {
                out.push_str(
                    "  - requires `## Acceptance Criteria` with all checkboxes ticked\n",
                );
            }
            if rule.requires_commits {
                out.push_str("  - requires at least one entry in `commits:`\n");
            }
            if !rule.allowed_from.is_empty() {
                out.push_str(&format!(
                    "  - allowed from: {}\n",
                    rule.allowed_from.join(", ")
                ));
            }
            if !rule.forbidden_from.is_empty() {
                out.push_str(&format!(
                    "  - forbidden from: {}\n",
                    rule.forbidden_from.join(", ")
                ));
            }
        }
        out.push('\n');
    }

    out
}

/// Wrap a managed body in sentinel comments. Used both for initial
/// generation and for `--fix` regeneration.
fn wrap_managed(body: &str) -> String {
    format!("{MANAGED_START}\n\n{body}{MANAGED_END}\n")
}

/// Render the full default file (prose + sentinel-fenced schema block).
pub fn render_full(schema: &Schema, rules: &TransitionRules) -> String {
    let mut out = String::new();
    out.push_str(DEFAULT_PROSE);
    out.push_str(&wrap_managed(&render_managed_body(schema, rules)));
    out
}

/// Locate the managed block within an existing AGENTS.md.
/// Returns `(start_byte_of_open_sentinel, end_byte_after_close_sentinel_line)`
/// when both sentinels are present and well-formed (start before end).
pub fn find_managed_span(text: &str) -> Option<(usize, usize)> {
    let start = text.find(MANAGED_START)?;
    let after_start = start + MANAGED_START.len();
    let end_rel = text[after_start..].find(MANAGED_END)?;
    let end = after_start + end_rel + MANAGED_END.len();
    // Consume one trailing newline if present so regeneration doesn't
    // leave a blank line after the close sentinel.
    let end = if text.as_bytes().get(end) == Some(&b'\n') {
        end + 1
    } else {
        end
    };
    Some((start, end))
}

/// Extract the inner managed body from an existing file (text between
/// the open sentinel + newline and the close sentinel). Returns
/// `None` if the sentinels are absent or malformed.
pub fn extract_managed_body(text: &str) -> Option<String> {
    let start = text.find(MANAGED_START)?;
    let after_start = start + MANAGED_START.len();
    let end_rel = text[after_start..].find(MANAGED_END)?;
    let inner = &text[after_start..after_start + end_rel];
    // Strip exactly one leading newline (from the sentinel-newline
    // we wrote) and one leading blank line, plus any trailing
    // whitespace before the close sentinel — symmetric with
    // `wrap_managed`.
    let inner = inner.strip_prefix('\n').unwrap_or(inner);
    let inner = inner.strip_prefix('\n').unwrap_or(inner);
    Some(inner.to_string())
}

/// Replace the managed span in `text` with a freshly-rendered block.
/// Preserves everything outside the sentinels byte-for-byte. If the
/// file has no sentinels, appends a fresh managed block at the end
/// (separated by a blank line).
pub fn regenerate_managed(text: &str, schema: &Schema, rules: &TransitionRules) -> String {
    let body = render_managed_body(schema, rules);
    let wrapped = wrap_managed(&body);
    match find_managed_span(text) {
        Some((start, end)) => {
            let mut out = String::with_capacity(text.len());
            out.push_str(&text[..start]);
            out.push_str(&wrapped);
            out.push_str(&text[end..]);
            out
        }
        None => {
            let mut out = String::from(text);
            if !out.ends_with('\n') {
                out.push('\n');
            }
            if !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(&wrapped);
            out
        }
    }
}

/// Returns true when the managed block in `text` matches what the
/// current schema + rules would produce. A file with no managed block
/// is considered drifted (the user opted in to AGENTS.md but is
/// missing the generated section).
pub fn managed_in_sync(text: &str, schema: &Schema, rules: &TransitionRules) -> bool {
    let expected = render_managed_body(schema, rules);
    match extract_managed_body(text) {
        Some(actual) => actual == expected,
        None => false,
    }
}

pub fn run_init(root: &Path, force: bool, json: bool) -> Result<()> {
    let path = agents_path(root);
    let parent = path
        .parent()
        .ok_or_else(|| anyhow::anyhow!("AGENTS.md path has no parent: {}", path.display()))?;
    fs::create_dir_all(parent)
        .with_context(|| format!("cannot create {}", parent.display()))?;

    let existed = path.is_file();
    if existed && !force {
        if json {
            println!(
                "{}",
                serde_json::to_string_pretty(&serde_json::json!({
                    "path": rel(root, &path),
                    "wrote": false,
                    "reason": "already exists; pass --force to overwrite",
                }))?
            );
        } else {
            eprintln!(
                "{} already exists; pass --force to overwrite.",
                rel(root, &path)
            );
        }
        bail!("{} already exists", rel(root, &path));
    }

    let schema = schema::load(root)?;
    let rules = transitions::load(root).unwrap_or_default();
    let content = render_full(&schema, &rules);

    fs::write(&path, content.as_bytes())
        .with_context(|| format!("cannot write {}", path.display()))?;

    if json {
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({
                "path": rel(root, &path),
                "wrote": true,
                "overwrote_existing": existed,
            }))?
        );
    } else {
        let verb = if existed { "Overwrote" } else { "Wrote" };
        println!("{} {}", verb, rel(root, &path));
    }
    Ok(())
}

fn rel(root: &Path, p: &Path) -> String {
    p.strip_prefix(root)
        .unwrap_or(p)
        .to_string_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn fresh() -> TempDir {
        let tmp = tempfile::tempdir().unwrap();
        fs::create_dir_all(tmp.path().join("issues")).unwrap();
        tmp
    }

    #[test]
    fn render_full_includes_sentinels_and_default_prose() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let out = render_full(&s, &r);
        assert!(out.contains(MANAGED_START));
        assert!(out.contains(MANAGED_END));
        assert!(out.contains("Never edit frontmatter manually"));
        assert!(out.contains("Refs-Issue: @<slug>"));
        // Default schema declares status enum — must surface.
        assert!(out.contains("`status`"));
        assert!(out.contains("in-progress"));
    }

    #[test]
    fn render_includes_body_sections_when_declared() {
        let mut s = schema::default_schema();
        s.body_sections.insert(
            "bug".to_string(),
            vec!["Reproduction".to_string(), "Acceptance Criteria".to_string()],
        );
        let out = render_full(&s, &TransitionRules::default());
        assert!(out.contains("**bug**"));
        assert!(out.contains("`## Reproduction`"));
        assert!(out.contains("`## Acceptance Criteria`"));
    }

    #[test]
    fn render_includes_transition_rules_when_declared() {
        let s = schema::default_schema();
        let r: TransitionRules = serde_yaml::from_str(
            "version: 1\nstatus_rules:\n  done:\n    requires_assignee: true\n    allowed_from: [testing]\n",
        )
        .unwrap();
        let out = render_full(&s, &r);
        assert!(out.contains("**→ done**"));
        assert!(out.contains("requires `assignee`"));
        assert!(out.contains("allowed from: testing"));
    }

    #[test]
    fn run_init_writes_file() {
        let tmp = fresh();
        run_init(tmp.path(), false, false).unwrap();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        assert!(p.is_file());
        let text = fs::read_to_string(&p).unwrap();
        assert!(text.contains(MANAGED_START));
    }

    #[test]
    fn run_init_refuses_overwrite_without_force() {
        let tmp = fresh();
        run_init(tmp.path(), false, false).unwrap();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        fs::write(&p, "user-edited content\n").unwrap();
        let err = run_init(tmp.path(), false, false).unwrap_err();
        assert!(err.to_string().contains("already exists"));
        // File untouched.
        assert_eq!(fs::read_to_string(&p).unwrap(), "user-edited content\n");
    }

    #[test]
    fn run_init_force_overwrites() {
        let tmp = fresh();
        let p = tmp.path().join(AGENTS_RELATIVE_PATH);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(&p, "stale\n").unwrap();
        run_init(tmp.path(), true, false).unwrap();
        let text = fs::read_to_string(&p).unwrap();
        assert!(text.contains(MANAGED_START));
        assert!(!text.contains("stale"));
    }

    #[test]
    fn regenerate_preserves_text_outside_sentinels() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let original = format!(
            "# Hand-written\n\nKeep me.\n\n{}\n\nold managed body\n{}\n\nAfter.\n",
            MANAGED_START, MANAGED_END
        );
        let regenerated = regenerate_managed(&original, &s, &r);
        assert!(regenerated.starts_with("# Hand-written\n\nKeep me.\n\n"));
        assert!(regenerated.contains("After.\n"));
        assert!(!regenerated.contains("old managed body"));
        assert!(regenerated.contains(MANAGED_START));
        assert!(regenerated.contains(MANAGED_END));
    }

    #[test]
    fn managed_in_sync_detects_drift() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let good = render_full(&s, &r);
        assert!(managed_in_sync(&good, &s, &r));

        // Mutate schema → drift.
        let mut s2 = s.clone();
        s2.body_sections
            .insert("bug".to_string(), vec!["Reproduction".to_string()]);
        assert!(!managed_in_sync(&good, &s2, &r));

        // Regenerating clears the drift.
        let fixed = regenerate_managed(&good, &s2, &r);
        assert!(managed_in_sync(&fixed, &s2, &r));
    }

    #[test]
    fn missing_sentinels_treated_as_drift() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        assert!(!managed_in_sync("just prose, no sentinels\n", &s, &r));
    }

    #[test]
    fn regenerate_appends_block_when_sentinels_missing() {
        let s = schema::default_schema();
        let r = TransitionRules::default();
        let original = "Plain prose, no managed block.\n";
        let out = regenerate_managed(original, &s, &r);
        assert!(out.starts_with(original));
        assert!(out.contains(MANAGED_START));
        assert!(managed_in_sync(&out, &s, &r));
    }
}
